trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '12-CI-CD-Pipelines/Azure-Devops/AKS'
    commandOptions: '-var="Name=$(Name)" -var="resourceGroup=$(resourceGroup)" -var="clientID=$(clientID)" -var="clientSecret=$(clientSecret)" -var="location=$(location)"'
    backendServiceArm: 'Pay-As-You-Go (f0595f93-8238-473c-a035-62cf6ce4b708)'
    backendAzureRmResourceGroupName: 'Dev10'
    backendAzureRmStorageAccountName: 'cloudskillstfstate92'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'tf/terraform.tfstate'

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '12-CI-CD-Pipelines/Azure-Devops/AKS'
    commandOptions: '-var="Name=$(Name)" -var="resourceGroup=$(resourceGroup)" -var="clientID=$(clientID)" -var="clientSecret=$(clientSecret)" -var="location=$(location)"'
    environmentServiceNameAzureRM: 'Pay-As-You-Go (f0595f93-8238-473c-a035-62cf6ce4b708)'
